spring.datasource.url: jdbc:postgresql://localhost/test-db
spring.datasource.username: test-user
spring.datasource.password: Apple123!!
spring.jpa.generate-ddl: true
logging:
  level:
    com.msms: DEBUG
    org.hibernate: WARN
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

system-config:
  watch-dir: /Users/Shared/tmp/test-dir
